version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 022499048865.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building Docker Image...
      - docker build -t andrei-counter .
      - docker tag andrei-counter:latest 022499048865.dkr.ecr.eu-west-1.amazonaws.com/andrei-counter:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 022499048865.dkr.ecr.eu-west-1.amazonaws.com/andrei-counter:latest

artifacts:
  files:
    - '**/'
